version: '3.4'

services:
  catalogdb:
    image: postgres
  catalogeapi:
    image: ${DOCKER_REGISTRY-}catalogeapi
    build:
      context: .
      dockerfile: CatalogeApi/Dockerfile

volumes:
  postgres_catalog:    
